//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArrayStore.Proxy {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Proxy.IArrayStore", CallbackContract=typeof(ArrayStore.Proxy.IArrayStoreCallback), SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface IArrayStore {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IArrayStore/Subscribe", ReplyAction="http://tempuri.org/IArrayStore/SubscribeResponse")]
        int Subscribe(sorter.ArrayType type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IArrayStore/Subscribe", ReplyAction="http://tempuri.org/IArrayStore/SubscribeResponse")]
        System.Threading.Tasks.Task<int> SubscribeAsync(sorter.ArrayType type);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IArrayStoreCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IArrayStore/Save")]
        void Save(int[] data);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IArrayStoreChannel : ArrayStore.Proxy.IArrayStore, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ArrayStoreClient : System.ServiceModel.DuplexClientBase<ArrayStore.Proxy.IArrayStore>, ArrayStore.Proxy.IArrayStore {
        
        public ArrayStoreClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public ArrayStoreClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public ArrayStoreClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ArrayStoreClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ArrayStoreClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public int Subscribe(sorter.ArrayType type) {
            return base.Channel.Subscribe(type);
        }
        
        public System.Threading.Tasks.Task<int> SubscribeAsync(sorter.ArrayType type) {
            return base.Channel.SubscribeAsync(type);
        }
    }
}
